---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
data:
  config.yaml: |
    adminHttp:
      port: 9190
      endpoints:
        prometheus: {}
    virtualClusters:
      my-cluster-proxy:
        # the virtual cluster is kafka proxy that sits between kafka clients and the real kafka cluster.  clients
        # connect to the virtual cluster rather than real cluster.
        clusterNetworkAddressConfigProvider:
          # this is the networking scheme used to present the virtual cluster on the network
          type: PortPerBrokerClusterNetworkAddressConfigProvider
          config:
            # this is the address the clients will refer to in their bootstrap.servers configuration.
            bootstrapAddress: localhost:9092
            brokerAddressPattern: proxy-service.kafka-proxy.svc.cluster.local
            brokerStartPort: 19092
            numberOfBrokerPorts: 3
        targetCluster:
          # declares the kafka cluster that is being proxied
          bootstrap_servers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
        logFrames: false
    defaultFilters:
    - encrypt
    filterDefinitions:
    - type: RecordEncryption
      name: encrypt
      config:
        # User: uncomment this section if you are using Vault.
        kms: FortanixDsmKmsService
        kmsConfig:
          endpointUrl: https://api.uk.smartkey.io
          apiKeySessionProvider:
            apiKey:
              passwordFile: /opt/proxy/encryption/kms-secrets/token.txt
        #experimental:
        #  resolvedAliasExpireAfterWriteSeconds: 60
        #  encryptionDekRefreshAfterWriteSeconds: 60
        selector: TemplateKekSelector
        selectorConfig:
          template: "KEK_${topicName}"
