apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka-proxy

resources:
- proxy-service.yaml
- proxy-config.yaml
- proxy-bootstrap.yaml
- proxy-broker-0.yaml
- self-signed-issuer.yaml
- server-certificate.yaml
- kroxy-server-keystore-password.yaml


