---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka-proxy

resources:
- proxy-namespace.yaml
- proxy-deployment.yaml
- proxy-pod-monitor.yaml
- proxy-encryption-kms-secret.yaml  # Note: This file is created during the PREPARE_KMS.md step


components:
- ../../kms/fortanix-dsm
